/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.alysee.tp_jdbc;

import java.util.List;
import javax.swing.DefaultListModel;

/**
 * Fenetre pour l'affichage des clients pour le médecin séléctionné, qui prend un médecin en paramétre
 * @author Alysee
 */
public class JFrameClientDunMedecin extends javax.swing.JFrame {

    private Medecin medecin;
    private DefaultListModel modelCLientDunMedecin = new DefaultListModel();

            
    public JFrameClientDunMedecin(Medecin medecin) {
        initComponents();
        this.medecin = medecin;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);//fermer la fenetre sans quitter le prog
        
        // Pour afficher le nom et prénom du médecin sélectionné
        jLabelNomMedecin.setText(this.medecin.getLastName() + " "+ this.medecin.getFirstName());
        
        /* 
            Instance de la Requete afin de récuperer la méthode "listeDesClientsDunMedecin()"
            Remplissage de la liste 
        */
        Requetes requetes = new Requetes();
        this.jListClientDunMedecin.setModel(this.modelCLientDunMedecin);
        List<Client> clients = requetes.listeDesClientsDunMedecin(medecin);
        for (Client cl : clients){
            modelCLientDunMedecin.addElement(cl);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelNomMedecin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListClientDunMedecin = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Client du médecin  : ");

        jListClientDunMedecin.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListClientDunMedecin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNomMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelNomMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNomMedecin;
    private javax.swing.JList jListClientDunMedecin;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
