/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.alysee.tp_jdbc;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Alysee
 */
public class JFrameGestionRV extends javax.swing.JFrame {

    private Medecin medecin;
    private DefaultListModel modelCreneau = new DefaultListModel();
    private DefaultListModel modelCLient = new DefaultListModel();
    private DefaultListModel modelRV = new DefaultListModel();


    public JFrameGestionRV(Medecin medecin) {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);//fermer la fenetre sans quitter le prog
        this.medecin = medecin;
        
        // Pour afficher le nom et prénom du médecin sélectionné
        jLabelNomMedecin.setText(this.medecin.getLastName() + " "+ this.medecin.getFirstName());

        /*
            Instance de la classe Requete, pou récupérer les méthodes "listeDesCreneauxDunMedecin()" et "listeDesClients()"
            Remplissages des deux listes
        */
        Requetes requetes = new Requetes();
        this.jListCreneaux.setModel(this.modelCreneau); 
        List<Creneau> creneaux = requetes.listeDesCreneauxDunMedecin(medecin);
        for (Creneau cr : creneaux){
            modelCreneau.addElement(cr);
        }
        
        this.jListClients.setModel(this.modelCLient);
        List<Client> clients = requetes.listeDesClients();
        for (Client cl : clients){
            modelCLient.addElement(cl);
        }
        
        this.jListRV.setModel(this.modelRV);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeltitle = new javax.swing.JLabel();
        jLabelNomMedecin = new javax.swing.JLabel();
        jLabeltitecre = new javax.swing.JLabel();
        jLabeltitrelisteclient = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCreneaux = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListClients = new javax.swing.JList();
        jLabeltitrerv = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListRV = new javax.swing.JList();
        jButtonInsererRV = new javax.swing.JButton();
        jButtonSuppRV = new javax.swing.JButton();
        jButtonInsererCreneau = new javax.swing.JButton();
        jButtonSuppCreneau = new javax.swing.JButton();
        jButtonInsererClient = new javax.swing.JButton();
        jButtonSuppClient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabeltitle.setText("Gestion des RV du médecin : ");

        jLabeltitecre.setText("Listes des creneaux : ");

        jLabeltitrelisteclient.setText("Liste des clients : ");

        jListCreneaux.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListCreneaux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListCreneauxMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListCreneaux);

        jListClients.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListClients);

        jLabeltitrerv.setText("Listes des RV : ");

        jListRV.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListRV);

        jButtonInsererRV.setText("Insertion");

        jButtonSuppRV.setText("Supression");

        jButtonInsererCreneau.setText("Insertion");
        jButtonInsererCreneau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsererCreneauActionPerformed(evt);
            }
        });

        jButtonSuppCreneau.setText("Suppression");
        jButtonSuppCreneau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuppCreneauActionPerformed(evt);
            }
        });

        jButtonInsererClient.setText("Insertion");
        jButtonInsererClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsererClientActionPerformed(evt);
            }
        });

        jButtonSuppClient.setText("Suppression");
        jButtonSuppClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuppClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jLabeltitecre)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonInsererClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSuppClient, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonInsererCreneau, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonSuppCreneau, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonSuppRV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonInsererRV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(22, 22, 22))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabeltitrelisteclient)
                        .addGap(178, 178, 178)
                        .addComponent(jLabeltitrerv))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabeltitle)
                        .addGap(26, 26, 26)
                        .addComponent(jLabelNomMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeltitle, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNomMedecin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeltitrelisteclient)
                    .addComponent(jLabeltitrerv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonInsererRV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSuppRV))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jLabeltitecre))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonInsererCreneau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSuppCreneau))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInsererClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSuppClient))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListCreneauxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListCreneauxMouseClicked
        /*
            Clique sur la liste des créneaux, pour afficher le rv lié au créneau
            Si on a sélectionné le créneau, alors on va instancié la classe Requete pour récuperer la méthode
            "listeDesRVDunCreneau" et l'ajouter à la liste des Rv
        */
        
        if (jListCreneaux.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Vous n'avez pas sélectionné de médecin", "Erreur", JOptionPane.ERROR_MESSAGE);

        }
        else {
            Creneau creneauSelectionne = (Creneau) modelCreneau.getElementAt(jListCreneaux.getSelectedIndex()); 
            // RemoveAllElements : pour éviter les doublons
            modelRV.removeAllElements();
            Requetes requetes = new Requetes();
            List<RV> rv = requetes.listeDesRVDunCreneau(creneauSelectionne);
            for (RV r : rv){
                modelRV.addElement(r);
            }
        }
    }//GEN-LAST:event_jListCreneauxMouseClicked

    private void jButtonInsererClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsererClientActionPerformed
        /*
            BOUTON INSERER CLIENT
            Ouvre la fenetre pour l'insertion d'un client qui prend en paramètre la liste des clients
        */
        JFrameInsererClient frameInsererClient = new JFrameInsererClient(jListClients);
        frameInsererClient.setVisible(true);
    }//GEN-LAST:event_jButtonInsererClientActionPerformed

    private void jButtonSuppCreneauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuppCreneauActionPerformed
        /*
            BOUTON SUPPRESSION D'UN CRENEAU
            Dès que l'on clique sur un creneau, on va instancier la classe Requete pour récuperer la méthode
            "supprimerCreneau()"
        */
        
        if (jListCreneaux.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Vous n'avez pas sélectionné de creneau", "Erreur", JOptionPane.ERROR_MESSAGE);

        }
        else {
            Creneau creneauSelectionne = (Creneau) jListCreneaux.getModel().getElementAt(jListCreneaux.getSelectedIndex());
            Requetes requetes = new Requetes();
            requetes.supprimerCreneau(creneauSelectionne);
            
            /*
                Rafraichir la liste des créneaux
            */
            this.modelCreneau.removeAllElements();
            List<Creneau> creneaux = requetes.listeDesCreneauxDunMedecin(medecin);
            for (Creneau cr : creneaux){
                this.modelCreneau.addElement(cr);
            }
            
        }
    }//GEN-LAST:event_jButtonSuppCreneauActionPerformed

    private void jButtonSuppClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuppClientActionPerformed
        /*
            BOUTON SUPPRIMER UN CLIENT
            On clique sur le client que l'on veut supprimer, on va instancier la classe Requete pour récuperer la 
            méthode "supprimerClient()" et ensuite on va rafraichir la liste
        */
     
        if (jListClients.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Vous n'avez pas sélectionné de client", "Erreur", JOptionPane.ERROR_MESSAGE);

        }
        else {
            Client clientSelectionne = (Client) jListClients.getModel().getElementAt(jListClients.getSelectedIndex());
            Requetes requetes = new Requetes();
            requetes.supprimerClient(clientSelectionne);
                
            /*
                Rafraichir la liste des clients
            */
            this.modelCLient.removeAllElements();
            List<Client> clients = requetes.listeDesClients();
            for (Client cl : clients){
                this.modelCLient.addElement(cl);
            }
       }
    }//GEN-LAST:event_jButtonSuppClientActionPerformed

    private void jButtonInsererCreneauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsererCreneauActionPerformed
        /*
           BOUTON INSERER CRENEAU
           Appel la fenetre "frameInsererCreneau" qui prend en parametre un medecin et la liste des créneaux
        */
        JFrameInsererCreneau frameInsererCreneau = new JFrameInsererCreneau(this.medecin, this.jListCreneaux);
        frameInsererCreneau.setVisible(true);
    }//GEN-LAST:event_jButtonInsererCreneauActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInsererClient;
    private javax.swing.JButton jButtonInsererCreneau;
    private javax.swing.JButton jButtonInsererRV;
    private javax.swing.JButton jButtonSuppClient;
    private javax.swing.JButton jButtonSuppCreneau;
    private javax.swing.JButton jButtonSuppRV;
    private javax.swing.JLabel jLabelNomMedecin;
    private javax.swing.JLabel jLabeltitecre;
    private javax.swing.JLabel jLabeltitle;
    private javax.swing.JLabel jLabeltitrelisteclient;
    private javax.swing.JLabel jLabeltitrerv;
    private javax.swing.JList jListClients;
    private javax.swing.JList jListCreneaux;
    private javax.swing.JList jListRV;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
