/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.alysee.tp_jdbc;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 * Fenetre pour l'insertion d'un créneau, qui à accès à la liste des créneaux en paramètre, ainsi qu'au médecin
 * @author Alysee
 */
public class JFrameInsererCreneau extends javax.swing.JFrame {

    private Medecin medecin;
    private JList jListCreneaux;

    
    public JFrameInsererCreneau(Medecin medecin, JList jlistCreneaux) {
        initComponents();
        this.medecin = medecin;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);//fermer la fenetre sans quitter le prog
        this.jListCreneaux = jlistCreneaux;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldVersion = new javax.swing.JTextField();
        jTextFieldHdeb = new javax.swing.JTextField();
        jTextFieldMindeb = new javax.swing.JTextField();
        jTextFieldHfin = new javax.swing.JTextField();
        jTextFieldMinfin = new javax.swing.JTextField();
        jButtonSauvegarder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Insertion d'un créneau");

        jLabel2.setText("Version : ");

        jLabel3.setText("Heure de début : ");

        jLabel4.setText("Minute de début : ");

        jLabel5.setText("Heure de fin :");

        jLabel6.setText("Minute de fin :");

        jButtonSauvegarder.setText("Sauvegarder");
        jButtonSauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSauvegarderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMinfin, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(jTextFieldMindeb)
                            .addComponent(jTextFieldHdeb)
                            .addComponent(jTextFieldVersion)
                            .addComponent(jTextFieldHfin, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSauvegarder)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jTextFieldVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                    .addComponent(jTextFieldHdeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(jTextFieldMindeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(jTextFieldHfin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldMinfin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSauvegarder)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSauvegarderActionPerformed
        /*
            BOUTON SAUVEGARDER
            Sauvegarde l'insertion d'un créneau
        */
         
        // On récupere le texte contenu dans les jTextField
        int version = Integer.parseInt(jTextFieldVersion.getText());
        int hdebut  = Integer.parseInt(jTextFieldHdeb.getText());
        int mdebut  = Integer.parseInt(jTextFieldMindeb.getText());
        int hfin    = Integer.parseInt(jTextFieldHfin.getText());
        int mfin    = Integer.parseInt(jTextFieldMinfin.getText());
        
         /* 
            On verifie s'il n'y a pas de jTextField vide,on va créer un créneau et instancier la classe Requete afin de récupèrer la méthode
            "insererCreneau()"
        */
        if (!jTextFieldVersion.getText().equals("") && !jTextFieldHdeb.getText().equals("") &&
                !jTextFieldMindeb.getText().equals("") && !jTextFieldHfin.getText().equals("")
                 && !jTextFieldMinfin.getText().equals("")){
            Creneau creneau = new Creneau(version, hdebut, mdebut, hfin, mfin, this.medecin.getId());
            Requetes requetes = new Requetes();
            requetes.insererCreneau(creneau);

            /*
                Pour rafraichir la liste avec le nouveau creneau que l'on vient de créer
            */
            DefaultListModel model = (DefaultListModel)this.jListCreneaux.getModel();
            model.removeAllElements();
            List<Creneau> creneaux = requetes.listeDesCreneauxDunMedecin(medecin);
            for (Creneau cr : creneaux){
                model.addElement(cr);
            }
            dispose(); //ferme la fenetre
        }
        else {
            JOptionPane.showMessageDialog(null, "Vous avez laisser un ou plusieurs champs vides", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSauvegarderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSauvegarder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldHdeb;
    private javax.swing.JTextField jTextFieldHfin;
    private javax.swing.JTextField jTextFieldMindeb;
    private javax.swing.JTextField jTextFieldMinfin;
    private javax.swing.JTextField jTextFieldVersion;
    // End of variables declaration//GEN-END:variables
}
